### PR TITLE
ISSD-1321

### PR DESCRIPTION
**Pull request by guivilarim**
ISSD-1321

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by renato-araujo-liferay** [comment]
ci:test:osb-site-initializer-partner-portal:nocompile

**Comment by renato-araujo-liferay** [comment]
LGTM. Since we are just adding some fixes and its a regular one. I'll not wait for ci:test.

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Pull request closed without merging**
