### PR TITLE
ISSD-1419 Created a field select to record its purpose

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-97](https://liferay.atlassian.net/browse/ISSD-97)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

15 files changed, 170 insertions(+), 10 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by pedroliveirav — APPROVED** [review]
It might be interesting to put a character limit on the description, but for me it's fine! Well done! 🚀

**Review by kylembischof — APPROVED** [review]
lgtm

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
ci:reevaluate:1287401_8176

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:forward

**Pull request closed without merging**
