### PR TITLE
ISSD-1141 Fixed behavior of the Trial button to be disabled if doesn't have trial SKU

### PR DESCRIPTION
**Pull request by welitonpe**
**[ISSD-1141](https://liferay.atlassian.net/jira/software/c/projects/ISSD/boards/789?selectedIssue=ISSD-1141)**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/142232#issuecomment-1763495472

**Pull request closed without merging**
