### PR TITLE
Refactor EVP - LRQA-83375 | master

### PR DESCRIPTION
**Pull request by heiditrindade**
https://liferay.atlassian.net/browse/LRQA-83375

### CODE REVIEW

**Review by MGabriellaS — COMMENTED** [review]
Thanks @heiditrindade  for working on this!
LGTM!
cc: @vinicius-paes

**Comment by heiditrindade** [comment]
ci:test:sf

**Comment by heiditrindade** [comment]
ci:reopen

**Comment by heiditrindade** [comment]
ci:reopen

**Pull request closed without merging**
