### PR TITLE
ISSD-765 [PRM] All content field - the message is displayed before fill in anything

### PR DESCRIPTION
**Pull request by netosantosbr**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by netosantosbr** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by netosantosbr** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
resent https://github.com/is-solutions-delivery/liferay-portal/pull/5137

**Pull request closed without merging**
