### PR TITLE
ISSD-1335 [CP 2.0] Error message when user doesn't have permissions to view page or page doesn't exist

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1335](https://liferay.atlassian.net/browse/ISSD-1335)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

7 files changed, 170 insertions(+), 18 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
