### PR TITLE
LPS-198628 [PRM] Wrong Currency sign shown the PRM opportunities' Deal Amount 

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
resent https://github.com/is-solutions-delivery/liferay-portal/pull/4935

**Pull request closed without merging**
