### PR TITLE
ISSD-1416 [Marketplace] Create Structure to consume Koroneiki APIs in Create License Key Form

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
Good job @joanagrego

**Comment by silasbsi** [comment]
@joanagrego could you check this conflicts?

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/143076)

**Pull request closed without merging**
