### PR TITLE
LPS-197571 [CP 2.0] Fix side navigation icons and project status

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-197571](https://liferay.atlassian.net/browse/LPS-197571)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]
Looks good!

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/141565

**Pull request closed without merging**
