### PR TITLE
ISSD-1499 [PRM] Dashboard the "Expiring Soon" field is not showing the value

### PR DESCRIPTION
**Pull request by netosantosbr**

### CODE REVIEW

**Review by Manda-vit — COMMENTED** [review]
I suggest to change the home template to try to fit all the components in there

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by netosantosbr** [comment]
ci:test:stable

**Comment by netosantosbr** [comment]
ci:test:revelant

**Comment by netosantosbr** [comment]
ci:test:relevant

**Comment by netosantosbr** [comment]
ci:test:sf

**Comment by netosantosbr** [comment]
ci:test:stable

**Comment by netosantosbr** [comment]
ci:test:relevant

**Review by caiosouza15 — COMMENTED** [review]
Good job @netosantosbr!  LGTM.

**Comment by Manda-vit** [comment]
ci:foward:force

**Comment by Manda-vit** [comment]
ci:forward:force

**Pull request closed without merging**
