### PR TITLE
LPD-27280 Rename

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:playwright

**Comment by kevenleone** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/is-solutions-delivery/liferay-portal/pull/5776)

**Pull request closed without merging**
