### PR TITLE
ISSD-1485 [CP 2.0] Fix success alert in key generation flow

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1485](https://liferay.atlassian.net/browse/ISSD-1485)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
