### PR TITLE
ISSD-2129 [CP 2.0] Created Mega Menu item for Users to Escalate a Ticket

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-2129](https://liferay.atlassian.net/browse/ISSD-2129)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 9 insertions(+)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Comment by jpince** [comment]
@samuelleolopes @kylembischof test failures seem unrelated?

[Wildfly](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872021/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/):
```Portal log assert failure, see above log for more information:  HHH000315: Exception executing batch [java.sql.BatchUpdateException: (conn=14) Duplicate entry '5168551695166835362-com.liferay.commerce.model.CommerceOrderT...' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)```

[ProjectTemplatesServiceBuilderTest.testBuildTemplateServiceBuilderCheckExports](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314280/testReport/com.liferay.project.templates.service.builder/ProjectTemplatesServiceBuilderTest/testBuildTemplateServiceBuilderCheckExports/):
```java.io.FileNotFoundException: http://www.liferay.com/dtd/liferay-service-builder_7_4_0.dtd```

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
