### PR TITLE
LPD-30817 [Marketplace] Create Site Initializer Workspace

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:help

**Pull request closed without merging**
