### PR TITLE
ISSD-1600 [CP 2.0] [Bug] Fixed Non-Prod environment type filter returning zero results on the DXP Activation Keys Table

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1600](https://liferay.atlassian.net/browse/ISSD-1600)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good to me!

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
