### PR TITLE
[TECHNICAL SUPPORT] LPS-202594 Questions: Multiple Submissions can be made from the same input

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-202594](https://liferay.atlassian.net/browse/LPS-202594)
It was possible to make several formsubmission by clicking on the submit button multiple times, as the button invokes form submission, I decided to keep the button disabled and only reallow it if the form submission fails resolving the issue at hand.

Please review my changes,

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
LGTM!

Thank you for this PR @NemethNorbert

**Comment by NemethNorbert** [comment]
Hey @is-solutions-delivery ,

It looks like the PR is stucked, can you forward it?
Thanks

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
