### PR TITLE
LPD-21116 Improving ellipsis button functionalities

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/148589#event-12273515419

**Pull request closed without merging**
