### PR TITLE
LPS-198964 [CP 2.0] Test Automated

### PR DESCRIPTION
**Pull request by joelrocha68**
Ticket: https://liferay.atlassian.net/browse/LPS-198965

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Review by styller1 — APPROVED** [review]
LGTM 🔥 🦖

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
