### PR TITLE
ISSD-1389 [PRM] Setup ARR fields for the Level Dashboard to get data from SFDC

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:stable

**Review by jairmedeiros — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Pull request closed without merging**
