### PR TITLE
ISSD-639 [CP 2.0] Created alert warning, if a duplicate user account

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-100](https://liferay.atlassian.net/browse/ISSD-100)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

7 files changed, 90 insertions(+), 4 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
Looks good!

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
resent: https://github.com/is-solutions-delivery/liferay-portal/pull/4990

**Pull request closed without merging**
