### PR TITLE
ISSD-1441 [CP 2.0] Fix delay when change complimentary key permission

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1441](https://liferay.atlassian.net/browse/ISSD-1441)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by styller1** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]
Looks good to me!

**Comment by kylembischof** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Comment by styller1** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:reevaluate:1297401_8504

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
