### PR TITLE
ISSD-1726 [CP 2.0] Change link in remove user modal

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1726](https://liferay.atlassian.net/browse/ISSD-1726)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
Hey Pedro, for this ticket its not just a url change, the actual text on the popup is not rendering as a link. Can you please take a look at that as well?

**Comment by kylembischof** [comment]
Discussed with Pedro on slack, we will need to add the url to the client extension for it to render correctly

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
