### PR TITLE
ISSD-659 - Add 'Delete' option to MDF request listings' kebab menu for CMM and CMD

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 25 insertions(+), 7 deletions(-)

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
