### PR TITLE
ISSD-1630 [CP 2.0] Fix errors in the behavior of the key generation flow

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1630](https://liferay.atlassian.net/browse/ISSD-1630)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by kylembischof** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Pull request closed without merging**
