### PR TITLE
LPD-28179 Save Liferay Versions on specification

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
Good job @joanagrego !!

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
