### PR TITLE
ISSD-1679 [Marketplace] Tooltip creation and download keys error message

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-1679](https://liferay.atlassian.net/browse/ISSD-1679)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by eliasantosf** [comment]
ci:close

**Pull request closed without merging**
