### PR TITLE
ISSD-2064 [CP 2.0] Fix team members edit flow on Japanese language

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-2064](https://liferay.atlassian.net/browse/ISSD-2064)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
