### PR TITLE
LPD-42363 Fixed copy link URL when sharing app in Marketplace

### PR DESCRIPTION
**Pull request by CalebJamesH**
But Fix [LPD-42363](https://liferay.atlassian.net/browse/LPD-42363)

### CODE REVIEW

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
