### PR TITLE
Refactor EVP-LRQA-83365 |Master

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-83365](https://liferay.atlassian.net/browse/LRQA-83365)

These test are failing due to this bug: [LPS-193373](https://liferay.atlassian.net/browse/LPS-193373)
VerifyStatusAfterRequestMoreInfo
CanFinanceUserEditOrganization

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
@heiditrindade  thank you for the review! I updated this PR with the requested changes!

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:test:sf

**Review by vinicius-paes — APPROVED** [review]

**Comment by vinicius-paes** [comment]
ci:forward

**Comment by MGabriellaS** [comment]
ci:forward

**Pull request closed without merging**
