### PR TITLE
LPD-43435 Remove productChannel parameters

### PR DESCRIPTION
**Pull request by eduardo-diniz**

### CODE REVIEW

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Review by kevenleone — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by eduardo-diniz** [comment]
ci:forward:force

**Pull request closed without merging**
