### PR TITLE
LRSD-5033 [Learn] Change side nav template to fit new json structure and move css to globalcss

### PR DESCRIPTION
**Pull request by lluk4z**

### CODE REVIEW

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by rtienpal** [comment]
looks good to me, please review it @joseabelenda

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/152011

**Pull request closed without merging**
