### PR TITLE
ISSD-1769[Marketplace] Fix when getting a trial app, is displayed a different text in the Next Step page

### PR DESCRIPTION
**Pull request by juliocezar96**
[ISSD-1769](https://liferay.atlassian.net/browse/ISSD-1769)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/144737

**Pull request closed without merging**
