### PR TITLE
LPS-197508 [PRM] Fix Partner Rep Name and Partner Name Email are appearing blank on Opportinities

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Pull request closed without merging**
