### PR TITLE
ISSD-1882[Marketplace] Tooltip with typos and alignment errors

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtask : [ISSD-1882](https://liferay.atlassian.net/browse/ISSD-1882)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 11 insertions(+), 6 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :fire: :fire_engine:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
