### PR TITLE
ISSD-1498 [PRM] Activity Location field only appears as 'Location' on Details Page

### PR DESCRIPTION
**Pull request by fernando-castelo**

### CODE REVIEW

**Comment by fernando-castelo** [comment]
ci:test:sf

**Comment by fernando-castelo** [comment]
ci:test:stable

**Comment by fernando-castelo** [comment]
ci:test:relevant

**Comment by fernando-castelo** [comment]
ci:test:stable

**Comment by fernando-castelo** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:forward:force

**Pull request closed without merging**
