### PR TITLE
ISSD-1889 [Marketplace] Added Publisher gate Custom Element Client Extension

### PR DESCRIPTION
**Pull request by welitonpe**
**[ISSD-1030](https://liferay.atlassian.net/browse/ISSD-1030)**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Review by juliocezar96 — APPROVED** [review]
Good job! 🤙

**Review by kevenleone — APPROVED** [review]
🔥 

LGTM

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
