### PR TITLE
LPS-200261 [CP 2.0] Test Automated 

### PR DESCRIPTION
**Pull request by joelrocha68**
Ticket: https://liferay.atlassian.net/browse/LPS-200261

### CODE REVIEW

**Review by styller1 — APPROVED** [review]
LGTM 🔥 🦖

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:close

**Pull request closed without merging**
