### PR TITLE
ISSD-1418 Updated the complimentary key option and translation

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-97](https://liferay.atlassian.net/browse/ISSD-97)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

3 files changed, 13 insertions(+), 9 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by samuelleolopes** [comment]
ci:forward:force

**Review by pedroliveirav — APPROVED** [review]
Nice work! 🚀

**Pull request closed without merging**
