### PR TITLE
ISSD-1335 [CP 2.0] Fixed validation of the number of accounts the organization

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1335](https://liferay.atlassian.net/browse/ISSD-1335)

ISSD-1335 Added user permission to view organization

- Is necessary for the FLS filter to work and releases access to the organizations the user belongs to.

  Manual steps will be required
  Go to:
  Control Panel > Roles > Regular Roles: User> User: Define Permissions > Users and Organizations

  ORGANIZATION: View = True

- ORGANIZATION-View-True

ISSD-1335 Fixed validation of the number of accounts the organization

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

3 files changed, 12 insertions(+), 2 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by kylembischof** [comment]
closing this PR since it did not work as hoped

**Pull request closed without merging**
