### PR TITLE
ISSD-1749 [CP 2.0] Add site navigation translations

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1749](https://liferay.atlassian.net/browse/ISSD-1749)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good!

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
