### PR TITLE
MP2 - Temporary Test Fix - ISSD-1572 | master

### PR DESCRIPTION
**Pull request by MathausC**
Due to [ISSD-1347](https://liferay.atlassian.net/browse/ISSD-1347) the `HeadlessSite.addSite()` macro is not able to create the Marketplace site. So, a temporary fix was needed so we could see the correct results from the tests on CI. After the completion of [ISSD-1572](https://liferay.atlassian.net/browse/ISSD-1572) we should revert all this commits.

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf
ci:test:relevant
ci:test:stable

**Comment by MathausC** [comment]
ci:stop

**Comment by MathausC** [comment]
ci:foward

**Comment by styller1** [comment]
LGTM ! 🔥 🦖

**Pull request closed without merging**
