### PR TITLE
LPD-27280 [Marketplace] Supporting DXP versions as virtual items tests

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:playwright:nocompile

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/is-solutions-delivery/liferay-portal/pull/5770)

**Pull request closed without merging**
