### PR TITLE
PRM Automated Test - ISSD-834 | master 

### PR DESCRIPTION
**Pull request by brunadmelo**
[ISSD-834](https://liferay.atlassian.net/browse/ISSD-834)

### CODE REVIEW

**Comment by brunadmelo** [comment]
ci:test:sf

**Comment by brunadmelo** [comment]
cc: @guivilarim, @kenduenwald

**Comment by guivilarim** [comment]
ci:test:osb-site-initializer-partner-portal:nocompile

**Review by guivilarim — COMMENTED** [review]
Looks good to me!

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
