### PR TITLE
LPS-195305 [CP 2.0] Create side navigation structure

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-195305](https://liferay.atlassian.net/browse/LPS-195305)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job @pedroliveirav

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]

**Comment by styller1** [comment]
the flaws in this PR are not related to the code produced

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/141342

**Pull request closed without merging**
