### PR TITLE
ISSD-1553 [PRM] Change the message about the claim on the MDF request detail page

### PR DESCRIPTION
**Pull request by fernando-castelo**

### CODE REVIEW

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Review by Manda-vit — COMMENTED** [review]
LGMT!

**Comment by Manda-vit** [comment]
ci:foward:force

**Comment by Manda-vit** [comment]
ci:foward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
