### PR TITLE
ISSD-723 [PRM] Add Claim Paid Date input field

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Comment by caiosouza15** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

19 files changed, 225 insertions(+), 172 deletions(-)

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by thaynam** [comment]
[resent](https://github.com/is-solutions-delivery/liferay-portal/pull/5283)

**Pull request closed without merging**
