### PR TITLE
ISSD-1555 [PRM] Update "Contact Us" on the PRM Site page footer Version 2

### PR DESCRIPTION
**Pull request by netosantosbr**

### CODE REVIEW

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
LGTM!

**Review by Manda-vit — COMMENTED** [review]
LGTM!

**Comment by Manda-vit** [comment]
ci:foward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
