### PR TITLE
LPD-18505 [Marketplace] Add Product Image Description as the Image Title

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPD-18505](https://liferay.atlassian.net/browse/LPD-18505)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
