### PR TITLE
ISSD-1577 [Marketplace] Creation of the modal structure

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-1577](https://liferay.atlassian.net/browse/ISSD-1577)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
Beautiful!

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Related to PR: https://github.com/brianchandotcom/liferay-portal/pull/143499

**Comment by eliasantosf** [comment]
ci:close

**Pull request closed without merging**
