### PR TITLE
ISSD-1361 [Marketplace] Custom fields adjustments

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
@LuanaKSilva, could you check if this error is related to what was developed in this PR?

**Comment by LuanaKSilva** [comment]
Hey @silasbsi, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142410

**Pull request closed without merging**
