### PR TITLE
LPS-197011 [CP 2.0] Subscription Term with startdate greater than enddate

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-197011](https://liferay.atlassian.net/browse/LPS-197011)

### CODE REVIEW

**Review by pedroliveirav — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/141241

**Comment by kevenleone** [comment]
ci:stop

**Pull request closed without merging**
