### PR TITLE
LPD-17468 [Marketplace] Add images priority by clicking on the arrow

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPD-16540](https://liferay.atlassian.net/browse/LPD-16540)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
