### PR TITLE
ISSD-52[Learn] create-learn-site-initializer

### PR DESCRIPTION
**Pull request by Andrefes565**

### CODE REVIEW

**Comment by nNilton** [comment]
Please remove all site initializer changes

**Comment by nNilton** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
co:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:testforwad

**Comment by Andrefes565** [comment]
ci:stop

**Pull request closed without merging**
