### PR TITLE
LPD-20219 Created integration with Analytics to get reports

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by welitonpe** [comment]
ci:test:sf

**Review by nNilton — APPROVED** [review]

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/148590

**Pull request closed without merging**
