### PR TITLE
ISSD-1380 [Marketplace] Adjusted the configuration to use the new environment variables approach in LXC

### PR DESCRIPTION
**Pull request by welitonpe**
**[ISSD-1380](https://liferay.atlassian.net/jira/software/c/projects/ISSD/boards/789?selectedIssue=ISSD-1380)**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by LuanaKSilva** [comment]
Hey @silasbsi, CI failed to run the tests. Please fire again. Thank you!

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
@LuanaKSilva could you check again?

**Comment by LuanaKSilva** [comment]
Hey @welitonpe and @silasbsi, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/143084

**Pull request closed without merging**
