### PR TITLE
ISSD-1345 [Marketplace] Fixed the behavior of the navigation bar buttons to not wrap the text

### PR DESCRIPTION
**Pull request by welitonpe**
[ISSD-1345](**[url](https://liferay.atlassian.net/browse/ISSD-1345)**)

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by LuanaKSilva** [comment]
Hey @welitonpe and @silasbsi, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by welitonpe** [comment]
Ok thanks, @LuanaKSilva.

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142720

**Pull request closed without merging**
