### PR TITLE
LRSD-4881 [Learn] Fix Navigation Menu Icons

### PR DESCRIPTION
**Pull request by lluk4z**

### CODE REVIEW

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/152476

**Pull request closed without merging**
