### PR TITLE
ISSD-1428 [Marketplace] The invited user is not listed in the account members table

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
Good job @JoMaAlves

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
@LuanaKSilva could you check if this error is related to this PR?

**Comment by LuanaKSilva** [comment]
Hey @silasbsi, CI failed to run the tests. Please fire again. Thank you!

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142859

**Pull request closed without merging**
