### PR TITLE
LPD-39184 Make the order accessible after a product deletion

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPD-39184](https://liferay.atlassian.net/browse/LPD-39184)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]

**Review by welitonpe — APPROVED** [review]

**Review by kevenleone — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
resent: #6019

**Pull request closed without merging**
