### PR TITLE
LPD-20574 [Marketplace] Create Solutions Dashboard table

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPD-20574](https://liferay.atlassian.net/browse/LPD-20574)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/148294

**Pull request closed without merging**
