### PR TITLE
ISSD-1320 [Marketplace] Adjust validations and banner, image card positions

### PR DESCRIPTION
**Pull request by juliocezar96**
[ISSD-1320](https://liferay.atlassian.net/browse/ISSD-1320)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

3 files changed, 19 insertions(+), 12 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]
Good job!

**Review by welitonpe — APPROVED** [review]
Good job :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
