### PR TITLE
ISSD-1335 [CP 2.0] Added user permission to view organization

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1335](https://liferay.atlassian.net/browse/ISSD-1335)

- ISSD-1335 Added user permission to view organization

      Is necessary for the FLS filter to work and releases access to the organizations the user belongs to.

      Manual steps will be required
      Go to:
      Control Panel > Roles > Regular Roles: User> User: Define Permissions > Users and Organizations

      ORGANIZATION: View = True

      
ORGANIZATION-View-True (1)

- ISSD-1335 Added validation for account Permission

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 9 insertions(+)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
@samuelleolopes is this latest commit https://github.com/is-solutions-delivery/liferay-portal/pull/5451/commits/487984e3d0bdd21691c6223e7ac5d6bd614a32d7 supposed to fix the issue Patricia found?

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by jennyhchen** [comment]
@samuelleolopes I pulled your JS changes into my working environment as I'm testing FLS right now and it seems to get past the "cannot view this project" page, but when I click on Activation Key > DXP to see if I can download a license key from a customer account, I'm not able to. I see an infinite "Loading..." page. I may be missing a configuration but the other tabs seem to load okay.

For the resource-permissions.json, can you put the manual steps of how to enable it in the control panel onto the ticket? (When more devs are working on the same code-base, it would be better if you put manual steps on the ticket for them without having to rebuild a whole site every time and add site-initializer configs via the JSON files for making release easier.) In my example, our tickets are semi-related so I want to be able to test my code along with yours.

**Comment by samuelleolopes** [comment]
> @samuelleolopes I pulled your JS changes into my working environment as I'm testing FLS right now and it seems to get past the "cannot view this project" page, but when I click on Activation Key > DXP to see if I can download a license key from a customer account, I'm not able to. I see an infinite "Loading..." page. I may be missing a configuration but the other tabs seem to load okay.
> 
> For the resource-permissions.json, can you put the manual steps of how to enable it in the control panel onto the ticket? (When more devs are working on the same code-base, it would be better if you put manual steps on the ticket for them without having to rebuild a whole site every time and add site-initializer configs via the JSON files for making release easier.) In my example, our tickets are semi-related so I want to be able to test my code along with yours.

hi Jenny, regarding the JS code, I am trying to solve the problem that is happening in UAT, I will send you another code as soon as possible.

**Comment by kylembischof** [comment]
@jennyhchen he added the manual steps in a comment. see the "Release Notes" section on the ticket description

**Pull request closed without merging**
