### PR TITLE
ISSD-765 [PRM] Fixing error message before fill in anything

### PR DESCRIPTION
**Pull request by jpcchaves**

### CODE REVIEW

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:stable

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
