### PR TITLE
ISSD-2694 [PRM] Create a Client Extension Spring Boot for Account Sync

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by amosfong** [comment]
Looks good, made a few small changes. Attempting to forward to Bchan 

https://github.com/amosfong/liferay-portal/pull/111

**Pull request closed without merging**
