### PR TITLE
ISSD-1383 [CP 2.0] Add informative alert to complimentary key generation

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1383](https://liferay.atlassian.net/browse/ISSD-1383)

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job @pedroliveirav

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
Looks good!

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:stop

**Review by kevenleone — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Pull request closed without merging**
