### PR TITLE
ISSD-1340 [PRM] FIXED dropdown menu is displayed as if there were options available

### PR DESCRIPTION
**Pull request by fernando-castelo**

### CODE REVIEW

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by netosantosbr** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by fernando-castelo** [comment]
ci:test:sf

**Comment by netosantosbr** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
