### PR TITLE
ISSD-1718 [CP 2.0] Added permission for the administrator user to generate license without being associated with the project

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1625](https://liferay.atlassian.net/browse/ISSD-1625)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

5 files changed, 34 insertions(+), 5 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Pull request closed without merging**
