### PR TITLE
ISSD-1245 [Marketplace] Change from headless admin to delivery in Solutions Marketplace Display page template

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtask: [ISSD-1245](https://liferay.atlassian.net/browse/ISSD-1245)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 15 insertions(+), 5 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
Good job @juliocezar96

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend:

**Pull request closed without merging**
