### PR TITLE
ISSD-1463 Divergences of information in the Customer Next Step flow

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by ocesar9** [comment]
https://liferay.atlassian.net/browse/ISSD-1463

**Comment by ocesar9** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job @ocesar9

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by LuanaKSilva** [comment]
Hey @silasbsi, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142905

**Pull request closed without merging**
