### PR TITLE
LPS-197640 [CP 2.0] Added link and style to text and logo image

### PR DESCRIPTION
**Pull request by samuelleolopes**

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
Looks good!

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/is-solutions-delivery/liferay-portal/pull/4895

**Pull request closed without merging**
