### PR TITLE
LPS-197502 [CP 2.0] Remove CIC roles in the team members table 

### PR DESCRIPTION
**Pull request by eduardo-diniz**
https://liferay.atlassian.net/browse/LPS-197502

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/141565

**Pull request closed without merging**
