### PR TITLE
ISSD-3021 [Testray] Fix Regression: System Unexpectedly Replaces Cases When Designing a Build

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Comment by JoMaAlves** [comment]
@joseabelenda could you take a look here, I believe that you can forward this already

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/147927

**Pull request closed without merging**
