### PR TITLE
LPD-20005 [Marketplace] Refactoring the app details page to fix errors when not signed in

### PR DESCRIPTION
**Pull request by joanagrego**
Related too -> https://liferay.atlassian.net/browse/LPD-20004

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
