### PR TITLE
LPS-203892 Getting Site Navigation Menu Items from API is not showing name when the type is node or URL

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
resent:https://github.com/is-solutions-delivery/liferay-portal/pull/5309

**Pull request closed without merging**
