### PR TITLE
LPS-197639 [PRM] Improve DataBufferLimitException for CronJob

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
