### PR TITLE
ISSD-2743 [PRM] Implement the scrollTo for Review step on MDF Request and Deal Registration forms

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-2743](https://liferay.atlassian.net/browse/ISSD-2743)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by eliasantosf** [comment]
Related to: https://github.com/brianchandotcom/liferay-portal/pull/147083

**Comment by eliasantosf** [comment]
ci:close

**Pull request closed without merging**
