### PR TITLE
LRSD-5540 [Learn] Color of liferay sites tab svg icons

### PR DESCRIPTION
**Pull request by lluk4z**

### CODE REVIEW

**Comment by lluk4z** [comment]
ci:test:sf

**Review by luisacmn — CHANGES_REQUESTED** [review]
var(--color-neutral-0)

**Comment by lluk4z** [comment]
ci:test:sf

**Review by luisacmn — APPROVED** [review]

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/152970

**Pull request closed without merging**
