### PR TITLE
ISSD-1812 Add Notification Conditions In MDF Request and Claim

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

4 files changed, 49 insertions(+), 11 deletions(-)

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
[resent](https://github.com/is-solutions-delivery/liferay-portal/pull/5214/commits)

**Pull request closed without merging**
