### PR TITLE
LPS-206532 Implement updateExternalReferenceCode for User

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Good to go from Headless side.

**Comment by nNilton** [comment]
resent:https://github.com/liferay-headless/liferay-portal/pull/1830

**Pull request closed without merging**
