### PR TITLE
ISSD-1590 [PRM] Fix Uncheck the activity on 'More Info Requested' status while editing makes the checkbox disappear

### PR DESCRIPTION
**Pull request by jpcchaves**

### CODE REVIEW

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
liferay/ci:test:stable

**Comment by jpcchaves** [comment]
ci:test:stable

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:stable

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward:force

**Comment by JoMaAlves** [comment]
resent: https://github.com/is-solutions-delivery/liferay-portal/pull/5227

**Pull request closed without merging**
