### PR TITLE
ISSD-204 [CP 2.0] add User role permissions

### PR DESCRIPTION
**Pull request by kylembischof**
also sorted other roles in alphabetical order

### CODE REVIEW

**Comment by kylembischof** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Review by pedroliveirav — APPROVED** [review]
Nice work!

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by kylembischof** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
