### PR TITLE
LPS-198606 [Marketplace] Change texts the Trial Next Steps Screen

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-193826](https://liferay.atlassian.net/browse/LPS-193826)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-198606 [FE] Change texts the Trial Next Steps Screen</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-198606">[FE] Change texts the Trial Next Steps Screen</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Low</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Julio Cezar</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Julio Cezar</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 3 insertions(+), 7 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
Good job @juliocezar96

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by LuanaKSilva** [comment]
Hey @juliocezar96, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142006

**Pull request closed without merging**
