### PR TITLE
LPD-43181 Remove Link for License Agreement

### PR DESCRIPTION
**Pull request by CalebJamesH**
Removed Link for License Agreement

### CODE REVIEW

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
ci:test:stable

**Comment by CalebJamesH** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
