### PR TITLE
LPD-41726 Feature Flag for Payment Methods

### PR DESCRIPTION
**Pull request by CalebJamesH**
https://liferay.atlassian.net/jira/software/c/projects/LPD/boards/256?quickFilter=4481&selectedIssue=LPD-41726

### CODE REVIEW

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
Thanks, @eduardo-diniz !

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
NOTE: source format test will NOT work until the Feature Flag has been implemented.

**Comment by welitonpe** [comment]
ci:forward

**Pull request closed without merging**
