### PR TITLE
LRSD-5891 [Learn] Publish Korean Translation that are already on liferay-learn repo

### PR DESCRIPTION
**Pull request by lluk4z**

### CODE REVIEW

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by lluk4z** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/is-solutions-delivery/liferay-portal/pull/5975

**Pull request closed without merging**
