### PR TITLE
LPS-197076 [Marketplace] Adjustment in price model definition

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-197076](https://issues.liferay.com/browse/LPS-197076)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
Good job @eliasantosf :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by LuanaKSilva** [comment]
Hey @eliasantosf, I analyzed the flaws and none of them were caused by your PR. Feel free to put it forward.

**Comment by silasbsi** [comment]
@eliasantosf send it directly to Brian.

**Pull request closed without merging**
