### PR TITLE
ISSD-1320 [Marketplace] Adjust banner size

### PR DESCRIPTION
**Pull request by juliocezar96**

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 195 insertions(+), 139 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job. @juliocezar96

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142717

**Pull request closed without merging**
