### PR TITLE
ISSD-1337 | Fix Customer Dashboard Redirection Route - Add Apps

### PR DESCRIPTION
**Pull request by ocesar9**
https://liferay.atlassian.net/browse/ISSD-1337

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by ocesar9** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job @ocesar9 Thanks :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
@LuanaKSilva could you check if this error is related to what was developed in this PR?

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by LuanaKSilva** [comment]
Hey @ocesar9 and @silasbsi, I analyzed the flaws, and none of them have anything to do with PR.
Feel free to put it forward.

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/142457

**Pull request closed without merging**
