### PR TITLE
ISSD-1906 [CP 2.0] Refactor perpetual dates display logic

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1906](https://liferay.atlassian.net/browse/ISSD-1906)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]
looks good

**Comment by kylembischof** [comment]
ci:forward

**Pull request closed without merging**
