### PR TITLE
LPS-197938 [PRM] CMM user could change the MDF with draft status to pending review with missing required fields

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by guivilarim** [comment]
ci:test:relevant

**Pull request closed without merging**
