### PR TITLE
ISSD-212 [CP 2.0] Test Automated

### PR DESCRIPTION
**Pull request by joelrocha68**
Ticket: https://liferay.atlassian.net/browse/ISSD-212

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Review by styller1 — APPROVED** [review]
LGTM 🔥 🦖

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
