### PR TITLE
ISSD-1678[Marketplace] The implementation of whether the product is in purchasable SKU

### PR DESCRIPTION
**Pull request by juliocezar96**
[ISSD-1678](https://liferay.atlassian.net/browse/ISSD-1678)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

11 files changed, 418 insertions(+), 5 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent https://github.com/brianchandotcom/liferay-portal/pull/144404#event-11064473963

**Pull request closed without merging**
