### PR TITLE
LPD-29926 [Marketplace] Improve App Publishing Flow for Licence Agreement

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
c:forward

**Comment by joanagrego** [comment]
c:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
