### PR TITLE
LPD-18631 [Marketplace] Click on client extensions link should redirect to a new tab

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPD-18631](https://liferay.atlassian.net/browse/LPD-18631)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
