### PR TITLE
LPD-20729 [Marketplace] Create Solution Details Component

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> https://liferay.atlassian.net/browse/LPD-20376

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job, @joanagrego

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
