### PR TITLE
ISSD-1653 [CP 2.0] Refactor multiselect component and remove loop

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1653](https://liferay.atlassian.net/browse/ISSD-1653)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Pull request closed without merging**
