### PR TITLE
Fix Tests PRM | ISSD-638 | master

### PR DESCRIPTION
**Pull request by LuanaKSilva**
Jira Link: [ISSD-638](https://liferay.atlassian.net/browse/ISSD-638)

### CODE REVIEW

**Comment by LuanaKSilva** [comment]
ci:test:osb-site-initializer-partner-portal

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Review by renato-araujo-liferay — APPROVED** [review]

**Comment by LuanaKSilva** [comment]
ci:forward

**Comment by LuanaKSilva** [comment]
ci:forward

**Pull request closed without merging**
