### PR TITLE
LPD-38753 Fixed categories in app-search-results and app-details

### PR DESCRIPTION
**Pull request by CalebJamesH**

### CODE REVIEW

**Comment by CalebJamesH** [comment]
ci:test:sf

**Comment by CalebJamesH** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
