### PR TITLE
ISSD-1556 [Marketplace] Add requests to license keys API and Table Pagination

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/143499

**Pull request closed without merging**
