### PR TITLE
ISSD-1967 Add replace for attribute in Taxonomy Category.

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:help

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/144734

**Pull request closed without merging**
