### PR TITLE
LPD-30131 Create Marketplace Helper fixture

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
Resent --> [brianchandotcom/liferay-portal/pull/152097](https://github.com/brianchandotcom/liferay-portal/pull/152097)

**Pull request closed without merging**
