### PR TITLE
MP2 Automation Test | ISSD-1253 | master

### PR DESCRIPTION
**Pull request by LuanaKSilva**
Jira Link: [ISSD-1253](https://liferay.atlassian.net/browse/ISSD-1253)

### CODE REVIEW

**Comment by LuanaKSilva** [comment]
ci:test:sf

**Comment by LuanaKSilva** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by LuanaKSilva** [comment]
ci:test:site-initializer-liferay-marketplace

**Review by renato-araujo-liferay — APPROVED** [review]
Thank you @LuanaKSilva

**Comment by renato-araujo-liferay** [comment]
Fails in ci:test:site-initializer-liferay-marketplace is a flake. 
moving these PR forward

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Pull request closed without merging**
