### PR TITLE
LPD-40230

### PR DESCRIPTION
**Pull request by eduardo-diniz**
https://liferay.atlassian.net/browse/LPD-40230

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:relevant

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by CalebJamesH** [comment]
Just starting reviewing :)

**Comment by CalebJamesH** [comment]
Just starting reviewing :)

**Pull request closed without merging**
