### PR TITLE
LPS-205901 [Site Initializer] Implement _addOrUpdateDataDefinition

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Pull request closed without merging**
