### PR TITLE
LPS-197960 [PRM] Create retry logic for Object Proxy Salesforce requests

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:forward:force

**Pull request closed without merging**
