### PR TITLE
LPS-196640 Delete CP's unused tests | master

### PR DESCRIPTION
**Pull request by itstali**
https://liferay.atlassian.net/browse/LPS-196640

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Comment by itstali** [comment]
ci:foward

**Comment by styller1** [comment]
ci:foward

**Comment by styller1** [comment]
ci:forward

**Comment by styller1** [comment]
ci:forward

**Comment by itstali** [comment]
ci:foward:force

**Comment by itstali** [comment]
ci:foward:force

**Comment by kevenleone** [comment]
Long time without updates

**Pull request closed without merging**
