### PR TITLE
ISSD-2213 Add API permission check to avoid Internal 500 error for non-authenticated customers

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/ISSD-2213

### CODE REVIEW

**Comment by jennyhchen** [comment]
ci:test

**Comment by kylembischof** [comment]
ci:test:sf

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
