### PR TITLE
u88

### PR DESCRIPTION
**Pull request by styller1**

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:testSuiteName:norebase

**Comment by styller1** [comment]
ci:stop

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal

**Comment by renato-araujo-liferay** [comment]
ci:test:osb-site-initializer-customer-portal:norebase

**Comment by renato-araujo-liferay** [comment]
ci:test:osb-site-initializer-customer-portal:norebase

**Pull request closed without merging**
