### PR TITLE
ISSD-3125 Compare Runs

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/nNilton/liferay-portal/pull/40

**Pull request closed without merging**
