### PR TITLE
[Learn] ISSD-1639 Design updates for Phase 2

### PR DESCRIPTION
**Pull request by tiago-ds**

### CODE REVIEW

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/145777

**Pull request closed without merging**
