### PR TITLE
ISSD-2154

### PR DESCRIPTION
**Pull request by rtienpal**

### CODE REVIEW

**Comment by rtienpal** [comment]
ci:test:fs

**Comment by rtienpal** [comment]
ci:test:sf

**Review by nNilton — CHANGES_REQUESTED** [review]

**Comment by rtienpal** [comment]
ci:test:sf

**Review by nNilton — APPROVED** [review]

**Comment by nNilton** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/145829

**Pull request closed without merging**
