### PR TITLE
ISSD-2361, ISSD-2363 [Learn]

### PR DESCRIPTION
**Pull request by tiago-ds**

### CODE REVIEW

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
ci:test:sf

**Review by abfranca — APPROVED** [review]

**Comment by tiago-ds** [comment]
ci:test:sf

**Comment by tiago-ds** [comment]
resent: [brianchandotcom#146714](https://github.com/brianchandotcom/liferay-portal/pull/146714)

**Pull request closed without merging**
