### PR TITLE
ISSD-1871 [Learn] Automate test for Learn

### PR DESCRIPTION
**Pull request by joelrocha68**
https://liferay.atlassian.net/browse/ISSD-1871

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Review by renato-araujo-liferay — APPROVED** [review]
LGTM! Thank you for this @joelrocha68 . Nice catch in organizing the code placing code order by name asc

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:test:stable

**Comment by joelrocha68** [comment]
ci:test:relevant

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward:force

**Comment by joelrocha68** [comment]
ci:forward:force

**Comment by joelrocha68** [comment]
#144730

**Pull request closed without merging**
