### PR TITLE
LPS-198434 [PRM] Rename "Payment Received" and "Amount Received" instances to "Amount Paid" for MDF Claim

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
a
ci:test:stable

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
