### PR TITLE
ISSD-1812 [PRM] Add Notification Conditions In MDF Request and Claim

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Manda-vit 

Just waiting for final round of tests to put forward!

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
