### PR TITLE
ISSD-1715 [CP 2.0] [Bug] Fixed When an administrator is removing another user from the team members

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1715](https://liferay.atlassian.net/browse/ISSD-1715)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 5 insertions(+), 3 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by pedroliveirav — APPROVED** [review]
Nice job! 🚀

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:forward

**Pull request closed without merging**
