### PR TITLE
ISSD-1808[Marketplace] Creation of the price list fragment

### PR DESCRIPTION
**Pull request by juliocezar96**
[ISSD-1808](https://liferay.atlassian.net/browse/ISSD-1808)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
