### PR TITLE
ISSD-1959 [PRM] Fix MDF dropdown does not work properly when changing the status

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
https://github.com/is-solutions-delivery/liferay-portal/pull/5462

**Pull request closed without merging**
