### PR TITLE
ISSD-2138 [MARKETPLACE] Change Solutions Developer Name to Custom Field

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:reevaluate:1257401_4539

**Comment by joanagrego** [comment]
ci:reevaluate:1257401_4539

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
