### PR TITLE
Refactor Questions LRQA-83030 | Master

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-83030](https://liferay.atlassian.net/browse/LRQA-83030)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@MGabriellaS please rebase this branch to resolve the conflict. Thank you!

**Comment by MGabriellaS** [comment]
@nikki-pru  done!

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
