### PR TITLE
COMMERCE-12837 [Marketplace] User global JS context for accountId

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12837

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
@smottal hey stefano, could you SF and force push here? I have updated our repo with latest code from upstream

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/143968

**Pull request closed without merging**
