### PR TITLE
ISSD-855 Add ViewPendingMarketingReviewStatusOptions test

### PR DESCRIPTION
**Pull request by KevinQueiroz**
[ISSD-855](https://liferay.atlassian.net/browse/ISSD-855) - PRMMDFClaimWorkflow#ViewPendingMarketingReviewStatusOptions

### CODE REVIEW

**Comment by KevinQueiroz** [comment]
ci:test:sf

**Comment by KevinQueiroz** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:osb-site-initializer-partner-portal:nocompile

**Comment by guivilarim** [comment]
The PR is looking fine to me. Just keep your eye on dividing the commits in blocks of logic when coding in different files and not letting them in an only commit.

**Review by guivilarim — COMMENTED** [review]
Looks good to me!

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
