### PR TITLE
ISSD-1864 [CP 2.0] Display the gravatar photo as the user profile menu icon

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-1864](https://liferay.atlassian.net/browse/ISSD-1864)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by kylembischof** [comment]
are we able to do it similar to Avatar.jsx like `const emailAddressMD5 = md5(emailAddress);` so we don't need that large bulk of md5 specific code?

**Comment by pedroliveirav** [comment]
> are we able to do it similar to Avatar.jsx like `const emailAddressMD5 = md5(emailAddress);` so we don't need that large bulk of md5 specific code?

Actually no, that's the way I was able to do it, as I'm working within a fragment there are some limitations and I couldn't import the md5 in any other way.

**Comment by kylembischof** [comment]
> Actually no, that's the way I was able to do it, as I'm working within a fragment there are some limitations and I couldn't > import the md5 in any other way.

okay, makes sense since its in a fragment.

**Comment by kylembischof** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Pull request closed without merging**
