### PR TITLE
LPD-26900 [Marketplace] Add New Solution Template Tests

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by joanagrego** [comment]
ci:test:playwright

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/is-solutions-delivery/liferay-portal/pull/5759)

**Pull request closed without merging**
