### PR TITLE
ISSD-1335 [CP 2.0] Refactored code and fixed to lock screen

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-1335](https://liferay.atlassian.net/browse/ISSD-1335)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 63 insertions(+), 69 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

@kylembischof I helped @samuelleolopes on that, it looks good!!!

**Comment by kylembischof** [comment]
awesome. Thanks for helping @kevenleone! looks good to me too!

**Comment by kylembischof** [comment]
ci:forward

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by samuelleolopes** [comment]
ci:forward:force

**Pull request closed without merging**
