### PR TITLE
LPS-185475 [Questions] Fix tests

### PR DESCRIPTION
**Pull request by joelrocha68**
https://liferay.atlassian.net/browse/LPS-185482
https://liferay.atlassian.net/browse/LPS-185475

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:questions:nocompile

**Comment by pyoo47** [comment]
@joelrocha68 I had to abort the `questions` test because it froze in CI

**Comment by pyoo47** [comment]
ci:test:questions

**Comment by joelrocha68** [comment]
ci:test:questions:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
